// <auto-generated>
// added auto-generated to suppress the warning we will visit this part later.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BlazorInputFile;


namespace CDNApplication.Models
{
    public class FileListEntryImplExtension : FileListEntryImpl
    {
        public MemoryStream MemoryData { get; set; }

        public FileListEntryImplExtension(MemoryStream memoryStream)
        {
            this.MemoryData = memoryStream;
        }
    }
}
