//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDNApplication.Resources.Pages {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UploadDocument {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadDocument() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CDNApplication.Resources.Pages.UploadDocument", typeof(UploadDocument).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        internal static string CDNLabel {
            get {
                return ResourceManager.GetString("CDNLabel", resourceCulture);
            }
        }
        
        internal static string SelectCertificateLabel {
            get {
                return ResourceManager.GetString("SelectCertificateLabel", resourceCulture);
            }
        }
        
        internal static string SelectCertificateDropDown {
            get {
                return ResourceManager.GetString("SelectCertificateDropDown", resourceCulture);
            }
        }
        
        internal static string SelectFileLabel {
            get {
                return ResourceManager.GetString("SelectFileLabel", resourceCulture);
            }
        }
        
        internal static string FileUploadedSuccessText {
            get {
                return ResourceManager.GetString("FileUploadedSuccessText", resourceCulture);
            }
        }
        
        internal static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        internal static string FileDescriptionLabel {
            get {
                return ResourceManager.GetString("FileDescriptionLabel", resourceCulture);
            }
        }
        
        internal static string AddYourDocumentsPanelHeading {
            get {
                return ResourceManager.GetString("AddYourDocumentsPanelHeading", resourceCulture);
            }
        }
        
        internal static string AddAnotherFileText {
            get {
                return ResourceManager.GetString("AddAnotherFileText", resourceCulture);
            }
        }
    }
}
