// <auto-generated>
// added auto-generated to suppress the warning we will visit this part later.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSF.Web.Client.Data
{
    public enum ArtifactType
    {
        JsonMetadata = 3,
        JsonDocument = 4,
        SignedJsonDocument = 5,
        None = 6
    }
}
