// <auto-generated>
// added auto-generated to suppress the warning we will visit this part later.
// </auto-generated>
using System;
using System.Collections.Generic;
namespace CSF.Web.Client.Data.DTO.MTAPI
{
    using System.Text.RegularExpressions;

    public class FileAttachment
    {

        public int Id { get; set; }
        public int ServiceRequestId { get; set; }
        public string Name { get; set; }

        public string EscapedName => Regex.Replace(this.Name, "[\"|\'|\\\\|/|\\||<|>|:|\\?|\\*|!]", "_");

        public int? Size { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }
    }
}
