// <auto-generated>
// added auto-generated to suppress the warning we will visit this part later.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSF.Web.Client.Data.DTO.reCaptcha
{
    public class RecaptchaResponse
    {
        public bool Success { get; set; }
        public DateTime Challenge_ts { get; set; }
        public string Hostname { get; set; }
    }
}
