// <auto-generated>
// added auto-generated to suppress the warning we will visit this part later.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CDNApplication.Data.DTO.MTAPI
{
    public class FileAttachment
    {
        public FileAttachment()
        {
        }

        public int Id { get; set; }
        public int ServiceRequestId { get; set; }
        public string Name { get; set; }
        public int? Size { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }
    }
}
